### PR TITLE
Add SUBSCRIPTION_EXTENDED and TEMPORARY_ENTITLEMENT_GRANT event types

### PR DESCRIPTION
**Pull request by dgalambos**
SUBSCRIPTION_EXTENDED and TEMPORARY_ENTITLEMENT_GRANT event types are missing from this module.

Documentation for new event types can be found here: https://www.revenuecat.com/docs/integrations/webhooks/event-types-and-fields#event-types

### CODE REVIEW

**Comment by dgalambos** [comment]
ping @iktakahiro

**Comment by iktakahiro** [comment]
@dgalambos thanks for your contribution! I'll merged you pull-request soon.

**Review by iktakahiro — APPROVED** [review]
Thank you for the pull request regarding the addition of the status type

**Comment by iktakahiro** [comment]
@dgalambos I merged your pull-request, and I've released [v1.2.2](https://github.com/iktakahiro/revcatgo/releases/tag/v1.2.2) 😉

**Pull request merged**
